[2021-08-25 17:09:44,664] {processor.py:162} INFO - Started process (PID=30) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:09:44,666] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:09:44,669] {logging_mixin.py:109} INFO - [2021-08-25 17:09:44,669] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:09:44,680] {logging_mixin.py:109} INFO - [2021-08-25 17:09:44,679] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:09:44,681] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:09:44,736] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.075 seconds
[2021-08-25 17:10:31,922] {processor.py:162} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:10:31,923] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:10:31,924] {logging_mixin.py:109} INFO - [2021-08-25 17:10:31,924] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:10:31,926] {logging_mixin.py:109} INFO - [2021-08-25 17:10:31,925] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:10:31,927] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:10:31,941] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 17:11:02,011] {processor.py:162} INFO - Started process (PID=401) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:11:02,013] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:11:02,014] {logging_mixin.py:109} INFO - [2021-08-25 17:11:02,013] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:11:02,016] {logging_mixin.py:109} INFO - [2021-08-25 17:11:02,015] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:11:02,017] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:11:02,051] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.043 seconds
[2021-08-25 17:11:32,825] {processor.py:162} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:11:32,826] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:11:32,826] {logging_mixin.py:109} INFO - [2021-08-25 17:11:32,826] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:11:32,829] {logging_mixin.py:109} INFO - [2021-08-25 17:11:32,828] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:11:32,830] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:11:32,848] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:12:03,047] {processor.py:162} INFO - Started process (PID=516) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:12:03,048] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:12:03,048] {logging_mixin.py:109} INFO - [2021-08-25 17:12:03,048] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:12:03,050] {logging_mixin.py:109} INFO - [2021-08-25 17:12:03,049] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:12:03,050] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:12:03,069] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2021-08-25 17:13:34,864] {processor.py:162} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:13:34,866] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:13:34,867] {logging_mixin.py:109} INFO - [2021-08-25 17:13:34,867] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:13:34,878] {logging_mixin.py:109} INFO - [2021-08-25 17:13:34,877] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:13:34,880] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:13:34,918] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.057 seconds
[2021-08-25 17:14:15,166] {processor.py:162} INFO - Started process (PID=347) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:14:15,167] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:14:15,168] {logging_mixin.py:109} INFO - [2021-08-25 17:14:15,167] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:14:15,170] {logging_mixin.py:109} INFO - [2021-08-25 17:14:15,169] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:14:15,170] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:14:15,188] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2021-08-25 17:14:45,442] {processor.py:162} INFO - Started process (PID=406) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:14:45,443] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:14:45,444] {logging_mixin.py:109} INFO - [2021-08-25 17:14:45,444] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:14:45,446] {logging_mixin.py:109} INFO - [2021-08-25 17:14:45,445] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:14:45,446] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:14:45,476] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.036 seconds
[2021-08-25 17:15:15,755] {processor.py:162} INFO - Started process (PID=458) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:15:15,756] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:15:15,757] {logging_mixin.py:109} INFO - [2021-08-25 17:15:15,757] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:15:15,759] {logging_mixin.py:109} INFO - [2021-08-25 17:15:15,759] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:15:15,760] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:15:15,776] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 17:15:45,983] {processor.py:162} INFO - Started process (PID=521) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:15:45,983] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:15:45,984] {logging_mixin.py:109} INFO - [2021-08-25 17:15:45,984] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:15:45,986] {logging_mixin.py:109} INFO - [2021-08-25 17:15:45,986] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:15:45,987] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:15:46,000] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:16:16,378] {processor.py:162} INFO - Started process (PID=573) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:16:16,379] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:16:16,380] {logging_mixin.py:109} INFO - [2021-08-25 17:16:16,380] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:16:16,382] {logging_mixin.py:109} INFO - [2021-08-25 17:16:16,381] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:16:16,383] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:16:16,401] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:16:46,902] {processor.py:162} INFO - Started process (PID=635) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:16:46,903] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:16:46,904] {logging_mixin.py:109} INFO - [2021-08-25 17:16:46,904] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:16:46,907] {logging_mixin.py:109} INFO - [2021-08-25 17:16:46,906] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:16:46,908] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:16:46,932] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.039 seconds
[2021-08-25 17:17:17,323] {processor.py:162} INFO - Started process (PID=696) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:17:17,324] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:17:17,324] {logging_mixin.py:109} INFO - [2021-08-25 17:17:17,324] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:17:17,326] {logging_mixin.py:109} INFO - [2021-08-25 17:17:17,325] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:17:17,327] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:17:17,345] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 17:18:57,839] {processor.py:162} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:18:57,840] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:18:57,841] {logging_mixin.py:109} INFO - [2021-08-25 17:18:57,841] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:18:57,844] {logging_mixin.py:109} INFO - [2021-08-25 17:18:57,843] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:18:57,844] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:18:57,882] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.045 seconds
[2021-08-25 17:33:19,306] {processor.py:162} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:33:19,307] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:33:19,308] {logging_mixin.py:109} INFO - [2021-08-25 17:33:19,307] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:33:19,310] {logging_mixin.py:109} INFO - [2021-08-25 17:33:19,309] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:33:19,310] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:33:19,333] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.031 seconds
[2021-08-25 17:36:06,630] {processor.py:162} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:36:06,631] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:36:06,631] {logging_mixin.py:109} INFO - [2021-08-25 17:36:06,631] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:36:06,634] {logging_mixin.py:109} INFO - [2021-08-25 17:36:06,634] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:36:06,635] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:36:06,671] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.054 seconds
[2021-08-25 17:36:46,440] {processor.py:162} INFO - Started process (PID=343) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:36:46,441] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:36:46,441] {logging_mixin.py:109} INFO - [2021-08-25 17:36:46,441] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:36:46,444] {logging_mixin.py:109} INFO - [2021-08-25 17:36:46,443] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:36:46,445] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:36:46,459] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 17:37:16,588] {processor.py:162} INFO - Started process (PID=392) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:37:16,589] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:37:16,589] {logging_mixin.py:109} INFO - [2021-08-25 17:37:16,589] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:37:16,591] {logging_mixin.py:109} INFO - [2021-08-25 17:37:16,591] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:37:16,591] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:37:16,609] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 17:37:46,836] {processor.py:162} INFO - Started process (PID=455) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:37:46,837] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:37:46,838] {logging_mixin.py:109} INFO - [2021-08-25 17:37:46,838] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:37:46,840] {logging_mixin.py:109} INFO - [2021-08-25 17:37:46,839] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:37:46,840] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:37:46,856] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 17:38:17,006] {processor.py:162} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:38:17,007] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:38:17,009] {logging_mixin.py:109} INFO - [2021-08-25 17:38:17,008] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:38:17,012] {logging_mixin.py:109} INFO - [2021-08-25 17:38:17,011] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:38:17,012] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:38:17,580] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.576 seconds
[2021-08-25 17:38:47,881] {processor.py:162} INFO - Started process (PID=570) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:38:47,882] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:38:47,883] {logging_mixin.py:109} INFO - [2021-08-25 17:38:47,883] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:38:47,885] {logging_mixin.py:109} INFO - [2021-08-25 17:38:47,884] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:38:47,885] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:38:47,898] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:39:18,133] {processor.py:162} INFO - Started process (PID=633) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:39:18,133] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:39:18,134] {logging_mixin.py:109} INFO - [2021-08-25 17:39:18,134] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:39:18,136] {logging_mixin.py:109} INFO - [2021-08-25 17:39:18,135] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:39:18,136] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:39:18,153] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 17:39:48,461] {processor.py:162} INFO - Started process (PID=686) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:39:48,462] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:39:48,462] {logging_mixin.py:109} INFO - [2021-08-25 17:39:48,462] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:39:48,464] {logging_mixin.py:109} INFO - [2021-08-25 17:39:48,464] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:39:48,465] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:39:48,478] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 17:40:18,609] {processor.py:162} INFO - Started process (PID=748) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:40:18,610] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:40:18,611] {logging_mixin.py:109} INFO - [2021-08-25 17:40:18,611] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:40:18,612] {logging_mixin.py:109} INFO - [2021-08-25 17:40:18,612] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:40:18,613] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:40:18,634] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:40:48,776] {processor.py:162} INFO - Started process (PID=810) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:40:48,776] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:40:48,777] {logging_mixin.py:109} INFO - [2021-08-25 17:40:48,777] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:40:48,779] {logging_mixin.py:109} INFO - [2021-08-25 17:40:48,778] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:40:48,779] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:40:48,793] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 17:41:18,864] {processor.py:162} INFO - Started process (PID=861) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:41:18,865] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:41:18,866] {logging_mixin.py:109} INFO - [2021-08-25 17:41:18,866] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:41:18,868] {logging_mixin.py:109} INFO - [2021-08-25 17:41:18,867] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:41:18,868] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:41:18,892] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.029 seconds
[2021-08-25 17:41:49,122] {processor.py:162} INFO - Started process (PID=924) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:41:49,123] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:41:49,124] {logging_mixin.py:109} INFO - [2021-08-25 17:41:49,123] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:41:49,125] {logging_mixin.py:109} INFO - [2021-08-25 17:41:49,125] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:41:49,126] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:41:49,142] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 17:42:19,395] {processor.py:162} INFO - Started process (PID=976) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:42:19,396] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:42:19,397] {logging_mixin.py:109} INFO - [2021-08-25 17:42:19,396] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:42:19,398] {logging_mixin.py:109} INFO - [2021-08-25 17:42:19,398] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:42:19,399] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:42:19,414] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 17:42:49,627] {processor.py:162} INFO - Started process (PID=1038) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:42:49,631] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:42:49,631] {logging_mixin.py:109} INFO - [2021-08-25 17:42:49,631] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:42:49,633] {logging_mixin.py:109} INFO - [2021-08-25 17:42:49,633] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:42:49,633] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:42:49,653] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.028 seconds
[2021-08-25 17:43:19,869] {processor.py:162} INFO - Started process (PID=1100) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:43:19,870] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:43:19,871] {logging_mixin.py:109} INFO - [2021-08-25 17:43:19,871] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:43:19,872] {logging_mixin.py:109} INFO - [2021-08-25 17:43:19,872] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:43:19,873] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:43:19,894] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:43:50,104] {processor.py:162} INFO - Started process (PID=1152) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:43:50,104] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:43:50,105] {logging_mixin.py:109} INFO - [2021-08-25 17:43:50,105] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:43:50,107] {logging_mixin.py:109} INFO - [2021-08-25 17:43:50,106] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:43:50,107] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:43:50,127] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:44:20,226] {processor.py:162} INFO - Started process (PID=1217) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:44:20,226] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:44:20,227] {logging_mixin.py:109} INFO - [2021-08-25 17:44:20,227] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:44:20,229] {logging_mixin.py:109} INFO - [2021-08-25 17:44:20,228] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:44:20,229] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:44:20,253] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.030 seconds
[2021-08-25 17:44:50,429] {processor.py:162} INFO - Started process (PID=1270) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:44:50,430] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:44:50,430] {logging_mixin.py:109} INFO - [2021-08-25 17:44:50,430] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:44:50,433] {logging_mixin.py:109} INFO - [2021-08-25 17:44:50,432] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:44:50,433] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:44:50,446] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 17:45:20,489] {processor.py:162} INFO - Started process (PID=1332) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:45:20,490] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:45:20,491] {logging_mixin.py:109} INFO - [2021-08-25 17:45:20,491] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:45:20,493] {logging_mixin.py:109} INFO - [2021-08-25 17:45:20,492] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:45:20,493] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:45:20,506] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 17:45:50,863] {processor.py:162} INFO - Started process (PID=1394) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:45:50,864] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:45:50,864] {logging_mixin.py:109} INFO - [2021-08-25 17:45:50,864] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:45:50,867] {logging_mixin.py:109} INFO - [2021-08-25 17:45:50,866] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:45:50,867] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:45:50,880] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 17:46:20,944] {processor.py:162} INFO - Started process (PID=1446) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:46:20,945] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:46:20,946] {logging_mixin.py:109} INFO - [2021-08-25 17:46:20,946] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:46:20,948] {logging_mixin.py:109} INFO - [2021-08-25 17:46:20,947] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:46:20,948] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:46:20,962] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:46:51,158] {processor.py:162} INFO - Started process (PID=1508) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:46:51,159] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:46:51,160] {logging_mixin.py:109} INFO - [2021-08-25 17:46:51,160] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:46:51,161] {logging_mixin.py:109} INFO - [2021-08-25 17:46:51,161] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:46:51,162] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:46:51,177] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 17:47:21,233] {processor.py:162} INFO - Started process (PID=1570) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:47:21,234] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:47:21,235] {logging_mixin.py:109} INFO - [2021-08-25 17:47:21,235] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:47:21,237] {logging_mixin.py:109} INFO - [2021-08-25 17:47:21,236] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:47:21,237] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:47:21,252] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:47:51,474] {processor.py:162} INFO - Started process (PID=1622) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:47:51,475] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:47:51,476] {logging_mixin.py:109} INFO - [2021-08-25 17:47:51,475] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:47:51,478] {logging_mixin.py:109} INFO - [2021-08-25 17:47:51,477] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:47:51,478] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:47:51,492] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 17:48:21,631] {processor.py:162} INFO - Started process (PID=1684) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:48:21,632] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:48:21,633] {logging_mixin.py:109} INFO - [2021-08-25 17:48:21,633] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:48:21,635] {logging_mixin.py:109} INFO - [2021-08-25 17:48:21,635] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:48:21,636] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:48:21,654] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2021-08-25 17:48:51,720] {processor.py:162} INFO - Started process (PID=1736) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:48:51,721] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:48:51,722] {logging_mixin.py:109} INFO - [2021-08-25 17:48:51,721] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:48:51,723] {logging_mixin.py:109} INFO - [2021-08-25 17:48:51,723] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:48:51,723] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:48:51,736] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 17:49:22,154] {processor.py:162} INFO - Started process (PID=1799) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:49:22,155] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:49:22,156] {logging_mixin.py:109} INFO - [2021-08-25 17:49:22,155] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:49:22,158] {logging_mixin.py:109} INFO - [2021-08-25 17:49:22,157] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:49:22,158] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:49:22,182] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.030 seconds
[2021-08-25 17:49:52,373] {processor.py:162} INFO - Started process (PID=1862) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:49:52,374] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:49:52,375] {logging_mixin.py:109} INFO - [2021-08-25 17:49:52,375] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:49:52,377] {logging_mixin.py:109} INFO - [2021-08-25 17:49:52,376] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:49:52,378] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:49:52,392] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:50:22,631] {processor.py:162} INFO - Started process (PID=1915) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:50:22,632] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:50:22,632] {logging_mixin.py:109} INFO - [2021-08-25 17:50:22,632] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:50:22,634] {logging_mixin.py:109} INFO - [2021-08-25 17:50:22,634] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:50:22,635] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:50:22,649] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:50:52,820] {processor.py:162} INFO - Started process (PID=1978) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:50:52,820] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:50:52,821] {logging_mixin.py:109} INFO - [2021-08-25 17:50:52,821] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:50:52,824] {logging_mixin.py:109} INFO - [2021-08-25 17:50:52,823] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:50:52,824] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:50:52,845] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 17:51:22,895] {processor.py:162} INFO - Started process (PID=2030) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:51:22,896] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:51:22,896] {logging_mixin.py:109} INFO - [2021-08-25 17:51:22,896] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:51:22,899] {logging_mixin.py:109} INFO - [2021-08-25 17:51:22,898] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:51:22,899] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:51:22,915] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 17:51:53,144] {processor.py:162} INFO - Started process (PID=2093) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:51:53,145] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:51:53,145] {logging_mixin.py:109} INFO - [2021-08-25 17:51:53,145] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:51:53,147] {logging_mixin.py:109} INFO - [2021-08-25 17:51:53,147] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:51:53,148] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:51:53,169] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 17:52:23,437] {processor.py:162} INFO - Started process (PID=2155) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:52:23,438] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:52:23,439] {logging_mixin.py:109} INFO - [2021-08-25 17:52:23,439] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:52:23,441] {logging_mixin.py:109} INFO - [2021-08-25 17:52:23,440] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:52:23,441] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:52:23,462] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 17:52:53,648] {processor.py:162} INFO - Started process (PID=2207) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:52:53,649] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:52:53,650] {logging_mixin.py:109} INFO - [2021-08-25 17:52:53,650] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:52:53,652] {logging_mixin.py:109} INFO - [2021-08-25 17:52:53,651] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:52:53,652] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:52:53,684] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.038 seconds
[2021-08-25 17:53:23,870] {processor.py:162} INFO - Started process (PID=2270) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:53:23,871] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:53:23,872] {logging_mixin.py:109} INFO - [2021-08-25 17:53:23,872] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:53:23,874] {logging_mixin.py:109} INFO - [2021-08-25 17:53:23,873] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:53:23,875] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:53:23,889] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:53:54,160] {processor.py:162} INFO - Started process (PID=2323) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:53:54,161] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:53:54,161] {logging_mixin.py:109} INFO - [2021-08-25 17:53:54,161] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:53:54,163] {logging_mixin.py:109} INFO - [2021-08-25 17:53:54,163] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:53:54,164] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:53:54,184] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:56:37,448] {processor.py:162} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:56:37,462] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:56:37,462] {logging_mixin.py:109} INFO - [2021-08-25 17:56:37,462] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:56:37,465] {logging_mixin.py:109} INFO - [2021-08-25 17:56:37,464] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:56:37,466] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:56:37,508] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.063 seconds
[2021-08-25 17:57:21,355] {processor.py:162} INFO - Started process (PID=344) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:57:21,356] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:57:21,357] {logging_mixin.py:109} INFO - [2021-08-25 17:57:21,356] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:57:21,358] {logging_mixin.py:109} INFO - [2021-08-25 17:57:21,358] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:57:21,359] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:57:21,373] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 17:57:51,540] {processor.py:162} INFO - Started process (PID=404) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:57:51,541] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:57:51,542] {logging_mixin.py:109} INFO - [2021-08-25 17:57:51,541] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:57:51,544] {logging_mixin.py:109} INFO - [2021-08-25 17:57:51,543] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:57:51,545] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:57:51,561] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 17:58:21,645] {processor.py:162} INFO - Started process (PID=456) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:58:21,646] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:58:21,647] {logging_mixin.py:109} INFO - [2021-08-25 17:58:21,646] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:58:21,649] {logging_mixin.py:109} INFO - [2021-08-25 17:58:21,648] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:58:21,650] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:58:21,677] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.036 seconds
[2021-08-25 17:58:51,883] {processor.py:162} INFO - Started process (PID=519) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:58:51,884] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:58:51,885] {logging_mixin.py:109} INFO - [2021-08-25 17:58:51,885] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:58:51,888] {logging_mixin.py:109} INFO - [2021-08-25 17:58:51,887] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:58:51,889] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:58:51,906] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 17:59:22,248] {processor.py:162} INFO - Started process (PID=581) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:59:22,249] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:59:22,250] {logging_mixin.py:109} INFO - [2021-08-25 17:59:22,249] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:59:22,252] {logging_mixin.py:109} INFO - [2021-08-25 17:59:22,251] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:59:22,252] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:59:22,269] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 17:59:52,639] {processor.py:162} INFO - Started process (PID=633) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:59:52,639] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 17:59:52,640] {logging_mixin.py:109} INFO - [2021-08-25 17:59:52,640] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:59:52,642] {logging_mixin.py:109} INFO - [2021-08-25 17:59:52,641] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 17:59:52,642] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 17:59:52,661] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 18:00:22,934] {processor.py:162} INFO - Started process (PID=696) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:00:22,935] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:00:22,936] {logging_mixin.py:109} INFO - [2021-08-25 18:00:22,935] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:00:22,937] {logging_mixin.py:109} INFO - [2021-08-25 18:00:22,937] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:00:22,938] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:00:22,950] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 18:00:53,010] {processor.py:162} INFO - Started process (PID=748) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:00:53,011] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:00:53,011] {logging_mixin.py:109} INFO - [2021-08-25 18:00:53,011] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:00:53,013] {logging_mixin.py:109} INFO - [2021-08-25 18:00:53,012] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:00:53,013] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:00:53,027] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:01:23,273] {processor.py:162} INFO - Started process (PID=810) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:01:23,274] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:01:23,275] {logging_mixin.py:109} INFO - [2021-08-25 18:01:23,275] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:01:23,277] {logging_mixin.py:109} INFO - [2021-08-25 18:01:23,276] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:01:23,277] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:01:23,295] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:01:53,500] {processor.py:162} INFO - Started process (PID=872) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:01:53,501] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:01:53,502] {logging_mixin.py:109} INFO - [2021-08-25 18:01:53,501] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:01:53,503] {logging_mixin.py:109} INFO - [2021-08-25 18:01:53,503] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:01:53,504] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:01:53,522] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 18:03:31,503] {processor.py:162} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:03:31,507] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:03:31,517] {logging_mixin.py:109} INFO - [2021-08-25 18:03:31,517] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:03:31,520] {logging_mixin.py:109} INFO - [2021-08-25 18:03:31,519] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:03:31,521] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:03:31,574] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.080 seconds
[2021-08-25 18:04:11,727] {processor.py:162} INFO - Started process (PID=343) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:04:11,728] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:04:11,729] {logging_mixin.py:109} INFO - [2021-08-25 18:04:11,728] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:04:11,731] {logging_mixin.py:109} INFO - [2021-08-25 18:04:11,730] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:04:11,731] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:04:11,746] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:04:42,126] {processor.py:162} INFO - Started process (PID=393) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:04:42,127] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:04:42,127] {logging_mixin.py:109} INFO - [2021-08-25 18:04:42,127] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:04:42,129] {logging_mixin.py:109} INFO - [2021-08-25 18:04:42,129] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:04:42,130] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:04:42,150] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 18:05:12,264] {processor.py:162} INFO - Started process (PID=455) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:05:12,264] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:05:12,265] {logging_mixin.py:109} INFO - [2021-08-25 18:05:12,265] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:05:12,267] {logging_mixin.py:109} INFO - [2021-08-25 18:05:12,266] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:05:12,267] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:05:12,282] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:05:42,447] {processor.py:162} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:05:42,448] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:05:42,449] {logging_mixin.py:109} INFO - [2021-08-25 18:05:42,449] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:05:42,451] {logging_mixin.py:109} INFO - [2021-08-25 18:05:42,450] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:05:42,451] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:05:42,467] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 18:06:12,714] {processor.py:162} INFO - Started process (PID=569) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:06:12,715] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:06:12,716] {logging_mixin.py:109} INFO - [2021-08-25 18:06:12,715] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:06:12,718] {logging_mixin.py:109} INFO - [2021-08-25 18:06:12,717] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:06:12,718] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:06:12,734] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 18:06:42,940] {processor.py:162} INFO - Started process (PID=631) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:06:42,940] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:06:42,941] {logging_mixin.py:109} INFO - [2021-08-25 18:06:42,941] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:06:42,943] {logging_mixin.py:109} INFO - [2021-08-25 18:06:42,942] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:06:42,943] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:06:42,964] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:07:13,186] {processor.py:162} INFO - Started process (PID=692) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:07:13,187] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:07:13,188] {logging_mixin.py:109} INFO - [2021-08-25 18:07:13,187] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:07:13,189] {logging_mixin.py:109} INFO - [2021-08-25 18:07:13,189] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:07:13,190] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:07:13,212] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.028 seconds
[2021-08-25 18:07:43,297] {processor.py:162} INFO - Started process (PID=745) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:07:43,298] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:07:43,299] {logging_mixin.py:109} INFO - [2021-08-25 18:07:43,299] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:07:43,302] {logging_mixin.py:109} INFO - [2021-08-25 18:07:43,301] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:07:43,303] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:07:43,331] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.036 seconds
[2021-08-25 18:08:13,551] {processor.py:162} INFO - Started process (PID=807) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:08:13,552] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:08:13,553] {logging_mixin.py:109} INFO - [2021-08-25 18:08:13,553] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:08:13,555] {logging_mixin.py:109} INFO - [2021-08-25 18:08:13,554] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:08:13,556] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:08:13,576] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:08:43,664] {processor.py:162} INFO - Started process (PID=859) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:08:43,664] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:08:43,665] {logging_mixin.py:109} INFO - [2021-08-25 18:08:43,665] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:08:43,667] {logging_mixin.py:109} INFO - [2021-08-25 18:08:43,666] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:08:43,667] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:08:43,685] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:09:13,871] {processor.py:162} INFO - Started process (PID=921) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:09:13,872] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:09:13,873] {logging_mixin.py:109} INFO - [2021-08-25 18:09:13,873] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:09:13,875] {logging_mixin.py:109} INFO - [2021-08-25 18:09:13,874] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:09:13,875] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:09:13,899] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.029 seconds
[2021-08-25 18:09:44,129] {processor.py:162} INFO - Started process (PID=983) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:09:44,130] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:09:44,130] {logging_mixin.py:109} INFO - [2021-08-25 18:09:44,130] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:09:44,132] {logging_mixin.py:109} INFO - [2021-08-25 18:09:44,132] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:09:44,133] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:09:44,148] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:10:14,357] {processor.py:162} INFO - Started process (PID=1036) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:10:14,360] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:10:14,361] {logging_mixin.py:109} INFO - [2021-08-25 18:10:14,361] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:10:14,363] {logging_mixin.py:109} INFO - [2021-08-25 18:10:14,362] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:10:14,363] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:10:14,376] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:10:44,550] {processor.py:162} INFO - Started process (PID=1098) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:10:44,551] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:10:44,551] {logging_mixin.py:109} INFO - [2021-08-25 18:10:44,551] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:10:44,553] {logging_mixin.py:109} INFO - [2021-08-25 18:10:44,553] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:10:44,554] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:10:44,567] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:11:14,789] {processor.py:162} INFO - Started process (PID=1150) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:11:14,790] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:11:14,790] {logging_mixin.py:109} INFO - [2021-08-25 18:11:14,790] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:11:14,792] {logging_mixin.py:109} INFO - [2021-08-25 18:11:14,792] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:11:14,793] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:11:14,805] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 18:11:44,985] {processor.py:162} INFO - Started process (PID=1212) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:11:44,985] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:11:44,986] {logging_mixin.py:109} INFO - [2021-08-25 18:11:44,986] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:11:44,988] {logging_mixin.py:109} INFO - [2021-08-25 18:11:44,988] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:11:44,989] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:11:45,010] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:12:15,301] {processor.py:162} INFO - Started process (PID=1274) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:12:15,302] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:12:15,302] {logging_mixin.py:109} INFO - [2021-08-25 18:12:15,302] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:12:15,304] {logging_mixin.py:109} INFO - [2021-08-25 18:12:15,304] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:12:15,305] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:12:15,319] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:12:45,606] {processor.py:162} INFO - Started process (PID=1326) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:12:45,606] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:12:45,607] {logging_mixin.py:109} INFO - [2021-08-25 18:12:45,607] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:12:45,609] {logging_mixin.py:109} INFO - [2021-08-25 18:12:45,608] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:12:45,609] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:12:45,623] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:13:15,709] {processor.py:162} INFO - Started process (PID=1388) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:13:15,709] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:13:15,710] {logging_mixin.py:109} INFO - [2021-08-25 18:13:15,710] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:13:15,712] {logging_mixin.py:109} INFO - [2021-08-25 18:13:15,712] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:13:15,712] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:13:15,735] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.028 seconds
[2021-08-25 18:13:46,105] {processor.py:162} INFO - Started process (PID=1449) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:13:46,106] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:13:46,107] {logging_mixin.py:109} INFO - [2021-08-25 18:13:46,107] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:13:46,110] {logging_mixin.py:109} INFO - [2021-08-25 18:13:46,109] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:13:46,110] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:13:46,126] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:14:16,178] {processor.py:162} INFO - Started process (PID=1501) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:14:16,179] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:14:16,180] {logging_mixin.py:109} INFO - [2021-08-25 18:14:16,180] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:14:16,182] {logging_mixin.py:109} INFO - [2021-08-25 18:14:16,181] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:14:16,182] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:14:16,198] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 18:14:46,599] {processor.py:162} INFO - Started process (PID=1564) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:14:46,599] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:14:46,600] {logging_mixin.py:109} INFO - [2021-08-25 18:14:46,600] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:14:46,602] {logging_mixin.py:109} INFO - [2021-08-25 18:14:46,601] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:14:46,602] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:14:46,615] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 18:15:16,852] {processor.py:162} INFO - Started process (PID=1616) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:15:16,853] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:15:16,853] {logging_mixin.py:109} INFO - [2021-08-25 18:15:16,853] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:15:16,856] {logging_mixin.py:109} INFO - [2021-08-25 18:15:16,855] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:15:16,856] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:15:16,873] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 18:15:47,175] {processor.py:162} INFO - Started process (PID=1678) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:15:47,176] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:15:47,177] {logging_mixin.py:109} INFO - [2021-08-25 18:15:47,177] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:15:47,179] {logging_mixin.py:109} INFO - [2021-08-25 18:15:47,178] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:15:47,179] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:15:47,193] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:16:17,611] {processor.py:162} INFO - Started process (PID=1740) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:16:17,611] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:16:17,612] {logging_mixin.py:109} INFO - [2021-08-25 18:16:17,612] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:16:17,614] {logging_mixin.py:109} INFO - [2021-08-25 18:16:17,614] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:16:17,615] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:16:17,639] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.031 seconds
[2021-08-25 18:16:47,670] {processor.py:162} INFO - Started process (PID=1793) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:16:47,671] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:16:47,672] {logging_mixin.py:109} INFO - [2021-08-25 18:16:47,672] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:16:47,674] {logging_mixin.py:109} INFO - [2021-08-25 18:16:47,673] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:16:47,674] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:16:47,688] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:17:17,920] {processor.py:162} INFO - Started process (PID=1854) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:17:17,921] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:17:17,921] {logging_mixin.py:109} INFO - [2021-08-25 18:17:17,921] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:17:17,923] {logging_mixin.py:109} INFO - [2021-08-25 18:17:17,923] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:17:17,924] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:17:17,943] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2021-08-25 18:17:48,333] {processor.py:162} INFO - Started process (PID=1907) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:17:48,334] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:17:48,335] {logging_mixin.py:109} INFO - [2021-08-25 18:17:48,335] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:17:48,338] {logging_mixin.py:109} INFO - [2021-08-25 18:17:48,337] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:17:48,339] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:17:48,359] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.029 seconds
[2021-08-25 18:18:18,599] {processor.py:162} INFO - Started process (PID=1970) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:18:18,600] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:18:18,601] {logging_mixin.py:109} INFO - [2021-08-25 18:18:18,600] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:18:18,603] {logging_mixin.py:109} INFO - [2021-08-25 18:18:18,602] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:18:18,603] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:18:18,618] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:18:49,019] {processor.py:162} INFO - Started process (PID=2033) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:18:49,020] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:18:49,020] {logging_mixin.py:109} INFO - [2021-08-25 18:18:49,020] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:18:49,023] {logging_mixin.py:109} INFO - [2021-08-25 18:18:49,022] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:18:49,023] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:18:49,042] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 18:19:19,512] {processor.py:162} INFO - Started process (PID=2085) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:19:19,514] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:19:19,514] {logging_mixin.py:109} INFO - [2021-08-25 18:19:19,514] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:19:19,517] {logging_mixin.py:109} INFO - [2021-08-25 18:19:19,517] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:19:19,518] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:19:19,539] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.030 seconds
[2021-08-25 18:19:49,989] {processor.py:162} INFO - Started process (PID=2148) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:19:49,990] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:19:49,990] {logging_mixin.py:109} INFO - [2021-08-25 18:19:49,990] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:19:49,992] {logging_mixin.py:109} INFO - [2021-08-25 18:19:49,992] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:19:49,993] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:19:50,010] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:20:20,115] {processor.py:162} INFO - Started process (PID=2200) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:20:20,116] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:20:20,116] {logging_mixin.py:109} INFO - [2021-08-25 18:20:20,116] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:20:20,118] {logging_mixin.py:109} INFO - [2021-08-25 18:20:20,117] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:20:20,119] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:20:20,132] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:20:50,311] {processor.py:162} INFO - Started process (PID=2263) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:20:50,312] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:20:50,312] {logging_mixin.py:109} INFO - [2021-08-25 18:20:50,312] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:20:50,314] {logging_mixin.py:109} INFO - [2021-08-25 18:20:50,314] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:20:50,315] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:20:50,329] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:21:20,719] {processor.py:162} INFO - Started process (PID=2323) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:21:20,720] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:21:20,720] {logging_mixin.py:109} INFO - [2021-08-25 18:21:20,720] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:21:20,722] {logging_mixin.py:109} INFO - [2021-08-25 18:21:20,722] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:21:20,723] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:21:20,737] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:21:51,010] {processor.py:162} INFO - Started process (PID=2379) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:21:51,011] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:21:51,012] {logging_mixin.py:109} INFO - [2021-08-25 18:21:51,011] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:21:51,013] {logging_mixin.py:109} INFO - [2021-08-25 18:21:51,013] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:21:51,014] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:21:51,026] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 18:22:21,170] {processor.py:162} INFO - Started process (PID=2443) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:22:21,171] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:22:21,172] {logging_mixin.py:109} INFO - [2021-08-25 18:22:21,171] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:22:21,174] {logging_mixin.py:109} INFO - [2021-08-25 18:22:21,173] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:22:21,174] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:22:21,188] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:22:51,694] {processor.py:162} INFO - Started process (PID=2496) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:22:51,695] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:22:51,696] {logging_mixin.py:109} INFO - [2021-08-25 18:22:51,695] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:22:51,697] {logging_mixin.py:109} INFO - [2021-08-25 18:22:51,697] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:22:51,698] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:22:51,713] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:23:21,812] {processor.py:162} INFO - Started process (PID=2558) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:23:21,813] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:23:21,813] {logging_mixin.py:109} INFO - [2021-08-25 18:23:21,813] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:23:21,815] {logging_mixin.py:109} INFO - [2021-08-25 18:23:21,814] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:23:21,816] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:23:21,830] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:23:52,199] {processor.py:162} INFO - Started process (PID=2621) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:23:52,200] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:23:52,200] {logging_mixin.py:109} INFO - [2021-08-25 18:23:52,200] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:23:52,203] {logging_mixin.py:109} INFO - [2021-08-25 18:23:52,202] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:23:52,203] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:23:52,223] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 18:24:22,634] {processor.py:162} INFO - Started process (PID=2674) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:24:22,635] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:24:22,635] {logging_mixin.py:109} INFO - [2021-08-25 18:24:22,635] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:24:22,637] {logging_mixin.py:109} INFO - [2021-08-25 18:24:22,637] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:24:22,637] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:24:22,658] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 18:24:52,759] {processor.py:162} INFO - Started process (PID=2736) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:24:52,760] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:24:52,761] {logging_mixin.py:109} INFO - [2021-08-25 18:24:52,761] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:24:52,763] {logging_mixin.py:109} INFO - [2021-08-25 18:24:52,763] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:24:52,764] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:24:52,787] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.030 seconds
[2021-08-25 18:25:23,199] {processor.py:162} INFO - Started process (PID=2788) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:25:23,200] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:25:23,200] {logging_mixin.py:109} INFO - [2021-08-25 18:25:23,200] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:25:23,202] {logging_mixin.py:109} INFO - [2021-08-25 18:25:23,202] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:25:23,203] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:25:23,215] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 18:25:53,385] {processor.py:162} INFO - Started process (PID=2852) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:25:53,386] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:25:53,387] {logging_mixin.py:109} INFO - [2021-08-25 18:25:53,387] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:25:53,388] {logging_mixin.py:109} INFO - [2021-08-25 18:25:53,388] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:25:53,389] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:25:53,413] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.030 seconds
[2021-08-25 18:26:23,596] {processor.py:162} INFO - Started process (PID=2915) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:26:23,596] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:26:23,597] {logging_mixin.py:109} INFO - [2021-08-25 18:26:23,597] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:26:23,599] {logging_mixin.py:109} INFO - [2021-08-25 18:26:23,598] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:26:23,599] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:26:23,614] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:26:53,870] {processor.py:162} INFO - Started process (PID=2967) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:26:53,871] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:26:53,871] {logging_mixin.py:109} INFO - [2021-08-25 18:26:53,871] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:26:53,873] {logging_mixin.py:109} INFO - [2021-08-25 18:26:53,872] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:26:53,873] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:26:53,887] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:27:24,152] {processor.py:162} INFO - Started process (PID=3029) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:27:24,153] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:27:24,153] {logging_mixin.py:109} INFO - [2021-08-25 18:27:24,153] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:27:24,155] {logging_mixin.py:109} INFO - [2021-08-25 18:27:24,155] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:27:24,155] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:27:24,176] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:27:54,798] {processor.py:162} INFO - Started process (PID=3091) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:27:54,799] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:27:54,799] {logging_mixin.py:109} INFO - [2021-08-25 18:27:54,799] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:27:54,801] {logging_mixin.py:109} INFO - [2021-08-25 18:27:54,801] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:27:54,802] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:27:54,817] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:28:24,946] {processor.py:162} INFO - Started process (PID=3143) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:28:24,947] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:28:24,948] {logging_mixin.py:109} INFO - [2021-08-25 18:28:24,947] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:28:24,950] {logging_mixin.py:109} INFO - [2021-08-25 18:28:24,949] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:28:24,950] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:28:24,963] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:28:55,153] {processor.py:162} INFO - Started process (PID=3205) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:28:55,153] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:28:55,154] {logging_mixin.py:109} INFO - [2021-08-25 18:28:55,154] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:28:55,156] {logging_mixin.py:109} INFO - [2021-08-25 18:28:55,155] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:28:55,156] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:28:55,171] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:29:25,471] {processor.py:162} INFO - Started process (PID=3257) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:29:25,472] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:29:25,472] {logging_mixin.py:109} INFO - [2021-08-25 18:29:25,472] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:29:25,475] {logging_mixin.py:109} INFO - [2021-08-25 18:29:25,474] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:29:25,475] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:29:25,491] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 18:29:55,667] {processor.py:162} INFO - Started process (PID=3319) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:29:55,668] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:29:55,669] {logging_mixin.py:109} INFO - [2021-08-25 18:29:55,669] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:29:55,671] {logging_mixin.py:109} INFO - [2021-08-25 18:29:55,670] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:29:55,671] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:29:55,689] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2021-08-25 18:30:25,763] {processor.py:162} INFO - Started process (PID=3381) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:30:25,764] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:30:25,765] {logging_mixin.py:109} INFO - [2021-08-25 18:30:25,765] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:30:25,769] {logging_mixin.py:109} INFO - [2021-08-25 18:30:25,767] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:30:25,769] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:30:25,794] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.034 seconds
[2021-08-25 18:30:55,994] {processor.py:162} INFO - Started process (PID=3434) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:30:55,995] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:30:55,996] {logging_mixin.py:109} INFO - [2021-08-25 18:30:55,996] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:30:55,998] {logging_mixin.py:109} INFO - [2021-08-25 18:30:55,997] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:30:55,998] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:30:56,012] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:31:26,333] {processor.py:162} INFO - Started process (PID=3496) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:31:26,333] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:31:26,334] {logging_mixin.py:109} INFO - [2021-08-25 18:31:26,334] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:31:26,336] {logging_mixin.py:109} INFO - [2021-08-25 18:31:26,335] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:31:26,336] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:31:26,350] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:31:56,714] {processor.py:162} INFO - Started process (PID=3548) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:31:56,714] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:31:56,715] {logging_mixin.py:109} INFO - [2021-08-25 18:31:56,715] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:31:56,717] {logging_mixin.py:109} INFO - [2021-08-25 18:31:56,716] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:31:56,717] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:31:56,730] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:32:26,861] {processor.py:162} INFO - Started process (PID=3610) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:32:26,861] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:32:26,862] {logging_mixin.py:109} INFO - [2021-08-25 18:32:26,862] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:32:26,864] {logging_mixin.py:109} INFO - [2021-08-25 18:32:26,863] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:32:26,864] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:32:26,885] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:32:57,406] {processor.py:162} INFO - Started process (PID=3672) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:32:57,407] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:32:57,408] {logging_mixin.py:109} INFO - [2021-08-25 18:32:57,408] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:32:57,411] {logging_mixin.py:109} INFO - [2021-08-25 18:32:57,410] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:32:57,411] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:32:57,431] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:33:27,792] {processor.py:162} INFO - Started process (PID=3724) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:33:27,793] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:33:27,793] {logging_mixin.py:109} INFO - [2021-08-25 18:33:27,793] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:33:27,795] {logging_mixin.py:109} INFO - [2021-08-25 18:33:27,794] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:33:27,796] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:33:27,809] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:33:58,333] {processor.py:162} INFO - Started process (PID=3787) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:33:58,334] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:33:58,334] {logging_mixin.py:109} INFO - [2021-08-25 18:33:58,334] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:33:58,336] {logging_mixin.py:109} INFO - [2021-08-25 18:33:58,336] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:33:58,337] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:33:58,354] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:34:28,750] {processor.py:162} INFO - Started process (PID=3850) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:34:28,751] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:34:28,751] {logging_mixin.py:109} INFO - [2021-08-25 18:34:28,751] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:34:28,753] {logging_mixin.py:109} INFO - [2021-08-25 18:34:28,753] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:34:28,754] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:34:28,770] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 18:34:58,897] {processor.py:162} INFO - Started process (PID=3902) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:34:58,898] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:34:58,898] {logging_mixin.py:109} INFO - [2021-08-25 18:34:58,898] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:34:58,900] {logging_mixin.py:109} INFO - [2021-08-25 18:34:58,900] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:34:58,900] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:34:58,916] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:35:29,439] {processor.py:162} INFO - Started process (PID=3964) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:35:29,440] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:35:29,441] {logging_mixin.py:109} INFO - [2021-08-25 18:35:29,441] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:35:29,443] {logging_mixin.py:109} INFO - [2021-08-25 18:35:29,442] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:35:29,444] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:35:29,462] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 18:35:59,848] {processor.py:162} INFO - Started process (PID=4017) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:35:59,850] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:35:59,850] {logging_mixin.py:109} INFO - [2021-08-25 18:35:59,850] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:35:59,852] {logging_mixin.py:109} INFO - [2021-08-25 18:35:59,852] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:35:59,853] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:35:59,872] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.026 seconds
[2021-08-25 18:36:30,489] {processor.py:162} INFO - Started process (PID=4080) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:36:30,489] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:36:30,490] {logging_mixin.py:109} INFO - [2021-08-25 18:36:30,490] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:36:30,492] {logging_mixin.py:109} INFO - [2021-08-25 18:36:30,492] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:36:30,493] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:36:30,509] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:37:01,028] {processor.py:162} INFO - Started process (PID=4142) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:37:01,029] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:37:01,030] {logging_mixin.py:109} INFO - [2021-08-25 18:37:01,030] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:37:01,032] {logging_mixin.py:109} INFO - [2021-08-25 18:37:01,032] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:37:01,033] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:37:01,049] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2021-08-25 18:37:31,742] {processor.py:162} INFO - Started process (PID=4195) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:37:31,743] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:37:31,743] {logging_mixin.py:109} INFO - [2021-08-25 18:37:31,743] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:37:31,745] {logging_mixin.py:109} INFO - [2021-08-25 18:37:31,745] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:37:31,746] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:37:31,764] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2021-08-25 18:38:02,280] {processor.py:162} INFO - Started process (PID=4258) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:38:02,281] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:38:02,281] {logging_mixin.py:109} INFO - [2021-08-25 18:38:02,281] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:38:02,283] {logging_mixin.py:109} INFO - [2021-08-25 18:38:02,283] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:38:02,284] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:38:02,296] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:38:32,737] {processor.py:162} INFO - Started process (PID=4312) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:38:32,737] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:38:32,738] {logging_mixin.py:109} INFO - [2021-08-25 18:38:32,738] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:38:32,740] {logging_mixin.py:109} INFO - [2021-08-25 18:38:32,740] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:38:32,741] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:38:32,757] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2021-08-25 18:39:03,142] {processor.py:162} INFO - Started process (PID=4375) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:39:03,142] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:39:03,143] {logging_mixin.py:109} INFO - [2021-08-25 18:39:03,143] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:39:03,145] {logging_mixin.py:109} INFO - [2021-08-25 18:39:03,144] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:39:03,145] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:39:03,158] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2021-08-25 18:39:33,315] {processor.py:162} INFO - Started process (PID=4438) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:39:33,316] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:39:33,317] {logging_mixin.py:109} INFO - [2021-08-25 18:39:33,317] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:39:33,318] {logging_mixin.py:109} INFO - [2021-08-25 18:39:33,318] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:39:33,319] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:39:33,332] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:40:03,604] {processor.py:162} INFO - Started process (PID=4490) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:40:03,604] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:40:03,605] {logging_mixin.py:109} INFO - [2021-08-25 18:40:03,605] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:40:03,607] {logging_mixin.py:109} INFO - [2021-08-25 18:40:03,606] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:40:03,607] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:40:03,620] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:40:34,049] {processor.py:162} INFO - Started process (PID=4552) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:40:34,051] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:40:34,051] {logging_mixin.py:109} INFO - [2021-08-25 18:40:34,051] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:40:34,053] {logging_mixin.py:109} INFO - [2021-08-25 18:40:34,052] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:40:34,053] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:40:34,068] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:41:04,328] {processor.py:162} INFO - Started process (PID=4613) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:41:04,330] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:41:04,330] {logging_mixin.py:109} INFO - [2021-08-25 18:41:04,330] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:41:04,332] {logging_mixin.py:109} INFO - [2021-08-25 18:41:04,332] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:41:04,333] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:41:04,358] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.032 seconds
[2021-08-25 18:41:34,874] {processor.py:162} INFO - Started process (PID=4666) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:41:34,875] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:41:34,876] {logging_mixin.py:109} INFO - [2021-08-25 18:41:34,875] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:41:34,878] {logging_mixin.py:109} INFO - [2021-08-25 18:41:34,877] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:41:34,878] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:41:34,902] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.031 seconds
[2021-08-25 18:42:04,969] {processor.py:162} INFO - Started process (PID=4728) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:42:04,970] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:42:04,971] {logging_mixin.py:109} INFO - [2021-08-25 18:42:04,971] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:42:04,973] {logging_mixin.py:109} INFO - [2021-08-25 18:42:04,972] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:42:04,974] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:42:04,994] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2021-08-25 18:42:35,202] {processor.py:162} INFO - Started process (PID=4781) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:42:35,202] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:42:35,203] {logging_mixin.py:109} INFO - [2021-08-25 18:42:35,203] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:42:35,205] {logging_mixin.py:109} INFO - [2021-08-25 18:42:35,204] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:42:35,205] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:42:35,219] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2021-08-25 18:43:05,380] {processor.py:162} INFO - Started process (PID=4843) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:43:05,381] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:43:05,382] {logging_mixin.py:109} INFO - [2021-08-25 18:43:05,382] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:43:05,384] {logging_mixin.py:109} INFO - [2021-08-25 18:43:05,384] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:43:05,384] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:43:05,398] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2021-08-25 18:43:35,589] {processor.py:162} INFO - Started process (PID=4905) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:43:35,590] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:43:35,590] {logging_mixin.py:109} INFO - [2021-08-25 18:43:35,590] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:43:35,593] {logging_mixin.py:109} INFO - [2021-08-25 18:43:35,592] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:43:35,593] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:43:35,608] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2021-08-25 18:44:05,670] {processor.py:162} INFO - Started process (PID=4957) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:44:05,671] {processor.py:613} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2021-08-25 18:44:05,672] {logging_mixin.py:109} INFO - [2021-08-25 18:44:05,672] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:44:05,674] {logging_mixin.py:109} INFO - [2021-08-25 18:44:05,673] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2021-08-25 18:44:05,674] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2021-08-25 18:44:05,689] {processor.py:170} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
